Port configuration incremental update support
Junchao-Mellanox/sonic-swss pull request #14
Opened 2022-03-10 09:57 UTC by Junchao-Mellanox

**What I did**

**Why I did it**

**How I verified it**

**Details if related**

2022-03-14 17:37 UTC, dgsudharsan commented
Can you please add description?

2022-03-15 03:39 UTC, dgsudharsan requested changes

2022-03-15 03:39 UTC, dgsudharsan commented on orchagent/portsorch.cpp
> +                    // Since we support inremental configuration, the admin_status is likely to be empty. However, configuring other field would cause
Typo incremental*

2022-03-15 03:39 UTC, dgsudharsan commented on orchagent/portsorch.cpp
> +                        if (p.m_autoneg != 1)
Instead of using numbers like 1 and 0, please use a macro or enum
AUTONEG_ON
AUTONEG_OFF
AUTONEG_NOT_SET

2022-03-15 03:44 UTC, Junchao-Mellanox commented on orchagent/portsorch.cpp
> +    auto status = setPortAutoNeg(p.m_port_id, an);
if SAI return not implement, should not log error

2022-03-15 03:44 UTC, Junchao-Mellanox commented on orchagent/portsorch.cpp
> +                        if (p.m_admin_state_up && p.m_autoneg == 1)
p.m_autoneg == 1 , change 1 to enum or const

2022-03-15 06:21 UTC, Junchao-Mellanox commented on cfgmgr/portmgr.cpp
> +            if (!exist)
Usually, there should be "mtu" and "admin_status" in config DB, so "set defaults blindly first" will probably cause "mtu" and "admin_status" being configured twice. I will add comment to explain this code, but I prefer to keep it. Let me know your comment.

2022-03-16 04:24 UTC, dgsudharsan approved these changes

2022-03-21 02:15 UTC, keboliu approved these changes

2022-03-22 08:01 UTC, closed without merging